[project]
name = "advent-of-code"
version = "0.1.0"
description = ""
authors = ["David M. Coe <david@davidmcoe.com>"]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "advent-of-code-data>=2.0.4",
    "jupyter>=1.1.1",
]
